### ISSUE TITLE
pick'n'mix request (taking justinfrankel/licecap updates and merging them to licecap-CE)

### ISSUE THREAD

**Issue by esaruoho** [dialex/licecap-CE#10]
@dialex any chance you could take the current code from Justin Frankel's version and merge it into licecap-CE? He made it compile properly by using macOS (fixed something in the xcodeproject).

they at https://github.com/justinfrankel/licecap/commits/master

**Comment by dialex** [comment]
Closing this repo. Let's use the original, as it seems to be active again. Hooray!
