### ISSUE TITLE
Update brew formula to use this fork

### ISSUE THREAD

**Issue by dialex** [dialex/licecap-CE#3]
We all know that the official github repo is no longer maintained. [Example.](https://github.com/justinfrankel/licecap/pull/8)

That's why we created this fork, to keep merging pull requests. Probably the next step would be to update the brew formula to pull releases from this fork instead.

Should we do it? Who can do it?

**Comment by esaruoho** [comment]
@dialex I dunno, I've seen 1.27 updated and just saw a big issue with macOS High Sierra fixed by Justin Frankel, apart from the icon + readme updates, does this fork bring more on the table?

**Comment by dialex** [comment]
I wasn't aware of that, aleluia! 😛 
You're right, this repo no longer adds value. I'll close it right away. Thanks for letting me know!
