### ISSUE TITLE
macOS - how to run Licecap-CE?

### ISSUE THREAD

**Issue by esaruoho** [dialex/licecap-CE#9]
How do I compile Licecap-CE for macOS High Sierra, please? @dialex

**Comment by dialex** [comment]
Honestly I don't know. The original author did not provided any instructions. I suggest you install Visual Studio for Mac and follow this instructions https://github.com/dialex/licecap-CE/blob/master/README.md

It's worth the try.

**Comment by esaruoho** [comment]
I installed Visual Studio for Mac and followed the instructions. Nothing happened when building either release or debug - all i get is that the project is not compatible with Visual Studio for Mac 2017, as witnessed by this shortcut, and that zlib/zconf.in.h is missing.
<img width="1440" alt="screen shot 2017-12-02 at 14 46 09" src="https://user-images.githubusercontent.com/4966687/33515719-9ade527c-d76f-11e7-9545-3fbc12d9ee7c.png">

**Comment by dialex** [comment]
You will have to install the original one then. You can use `brew` for that or download from their official website. Sorry I can't help you more than that 😶

**Comment by esaruoho** [comment]
I opened the XcodeProject in the Licecap-CE folder but that just outputs 46 warnings and 1 error and build fails.. i guess i'll see if i can boot the original version.

@dialex did you note, btw, that the original Licecap has been updated to 1.27?

**Comment by dialex** [comment]
Closing this repo. Let's use the original, as it seems to be active again. Hooray!
